version: '3.1'

services:
    db:
        restart: on-failure
        image: postgres:12-alpine
        environment:
          - POSTGRES_DB=$DB_NAME
          - POSTGRES_USER=$DB_USER
          - POSTGRES_PASSWORD=$DB_PASSWORD
        volumes:
          - $HOME/.docker-volumes/test/postgres:/var/lib/postgresql/data
        ports:
          - 5432:$DB_PORT

    php:
        build: .
        links:
            - db
        depends_on:
            - db
        environment:
          - LOCAL_MODE=0
        ports:
            - 8080:$PORT